[package]
name = "gvrtex-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gvrtex"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
gvrtex = "0.1.2"
color-print = "0.3.7"
